version: "3.4"
services:
    mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - '3306:3306'
      env_file:
        - docker.env
      volumes:
          - ${MYSQL_VOLUME:-./data/mysql}:/var/lib/mysql
    nginx:
        image: 'nginx:1.20'
        ports:
          - '80:80'
          - '443:443'
        restart: always
        volumes:
            - ${ROOT_DIR:-.}/:/var/www
            - ${BUILD_CONTEXT:-.}/docker-images/nginx-extended/default.conf:/etc/nginx/conf.d/default.conf
            - ${BUILD_CONTEXT:-.}/docker-images/nginx-extended/ssl/localhost.crt:/etc/nginx/localhost.crt
            - ${BUILD_CONTEXT:-.}/docker-images/nginx-extended/ssl/localhost.key:/etc/nginx/localhost.key
    php-fpm:
        build:
          context: .
          dockerfile: ./docker-images/php-extended/Dockerfile
        image: "php-fpm"
        container_name: "php-fpm-kafka"
        env_file:
          - docker.env
        restart: always
        volumes:
            - ${BUILD_CONTEXT:-.}/docker-images/php-extended/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ${ROOT_DIR:-.}/:/var/www
        depends_on:
          - mysql
          - nginx
        command: [ "php-fpm" ]
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - 22181:2181

    kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    pma:
      image: 'phpmyadmin/phpmyadmin:latest'
      ports:
        - '8090:80'
      env_file:
        - docker.env